// <auto-generated />
using System;
using ClubBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubBooking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525214121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ClubBooking.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20d29a28-8243-4455-837c-ffb8821bbc72"),
                            Address = "ул. Ленина, 10"
                        },
                        new
                        {
                            Id = new Guid("96b152c1-150c-4127-9d64-4b37a5a63a31"),
                            Address = "пр. Победы, 25"
                        });
                });

            modelBuilder.Entity("ClubBooking.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd2b0199-6521-487a-8e88-06d53e6cb658"),
                            ClubId = new Guid("20d29a28-8243-4455-837c-ffb8821bbc72"),
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = new Guid("a21a26ac-de07-4197-94eb-e3166dca72c4"),
                            ClubId = new Guid("96b152c1-150c-4127-9d64-4b37a5a63a31"),
                            SeatNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f404e631-0074-46f9-9991-0b6b3659ae95"),
                            ClubId = new Guid("20d29a28-8243-4455-837c-ffb8821bbc72"),
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = new Guid("51436f26-07a7-4268-9bf0-473acce24966"),
                            ClubId = new Guid("96b152c1-150c-4127-9d64-4b37a5a63a31"),
                            SeatNumber = 2
                        },
                        new
                        {
                            Id = new Guid("8363ccd1-6677-4bd1-a19d-ca8f13b6ed96"),
                            ClubId = new Guid("20d29a28-8243-4455-837c-ffb8821bbc72"),
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = new Guid("ee925dc7-b981-4aed-b741-5b63e0e8a2d4"),
                            ClubId = new Guid("96b152c1-150c-4127-9d64-4b37a5a63a31"),
                            SeatNumber = 3
                        },
                        new
                        {
                            Id = new Guid("e80f9ee8-feba-485c-b951-0110ae648c76"),
                            ClubId = new Guid("20d29a28-8243-4455-837c-ffb8821bbc72"),
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = new Guid("4b3936b2-b6e9-47bd-957e-608df0e3ad0e"),
                            ClubId = new Guid("96b152c1-150c-4127-9d64-4b37a5a63a31"),
                            SeatNumber = 4
                        },
                        new
                        {
                            Id = new Guid("4009150d-c6d0-4d26-9939-cd7cf8f82a55"),
                            ClubId = new Guid("20d29a28-8243-4455-837c-ffb8821bbc72"),
                            SeatNumber = 5
                        },
                        new
                        {
                            Id = new Guid("acde79db-0594-4ffa-a730-6b3527131dff"),
                            ClubId = new Guid("96b152c1-150c-4127-9d64-4b37a5a63a31"),
                            SeatNumber = 5
                        });
                });

            modelBuilder.Entity("ClubBooking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClubBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("ClubBooking.Domain.Entities.Seat", "Seat")
                        .WithMany("Bookings")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubBooking.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClubBooking.Domain.Entities.Seat", b =>
                {
                    b.HasOne("ClubBooking.Domain.Entities.Club", "Club")
                        .WithMany("Seats")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubBooking.Domain.Entities.Club", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("ClubBooking.Domain.Entities.Seat", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ClubBooking.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
